import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_android_tools_build_gradle: String = "4.0.0-alpha01"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val junit_junit: String = "4.12"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0"

    const val kotlin_android_extensions_runtime: String = "1.3.60-eap-25"
        // available: "1.3.60-eap-143"

    const val desugar_jdk_libs_configuration: String = "0.5.0"

    const val kotlin_android_extensions: String = "1.3.60-eap-25" // available: "1.3.60-eap-143"

    const val kotlin_gradle_plugin: String = "1.3.60-eap-25" // available: "1.3.60-eap-143"

    const val kotlin_stdlib_jdk7: String = "1.3.60-eap-143"

    const val constraintlayout: String = "1.1.3"

    const val desugar_jdk_libs: String = "1.0.1"

    const val espresso_core: String = "3.2.0"

    const val lint_gradle: String = "27.0.0-alpha01"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.1.0"

    const val aapt2: String = "4.0.0-alpha01-5910961"

    /**
     * Current version: "5.6.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.4"
}
